
FROM python:3.10.1-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install protobuf==3.20.*
COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py"]