FROM python:3.10.1-slim

WORKDIR /app

RUN apt-get update

RUN apt-get update && apt-get install -y libxml2-dev libxslt1-dev antiword unrtf poppler-utils tesseract-ocr \
flac ffmpeg lame libmad0 libsox-fmt-mp3 sox libjpeg-dev swig 

RUN pip install aiohttp asyncio aiofiles uvicorn starlette textract python-pptx xlrd docx2txt
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip3 install torch torchvision torchaudio

COPY . .

EXPOSE 8080

CMD ["python", "main.py"]